replicaCount: 1

postgres:
  databaseName: ytdb

weatherApp:
  image:
    repository: demo
    pullPolicy: IfNotPresent
    tag: latest

postgresVolume:
  persistentVolumeClaim:
    storageSize: 500Mi  #1Gi

  persistentVolume:
    storageSize: 500Mi
    pathOnHost: /Library/PostgreSQL/16/data

  mountPath: /Library/PostgreSQL/16/data
