apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-weather-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-weather-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-weather-app
    spec:
      containers:
        - name: {{ .Release.Name }}-weather-app-container
          image: {{ .Values.weatherApp.image.repository }}:{{ .Values.weatherApp.image.tag }}
          imagePullPolicy: {{ .Values.weatherApp.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ include "my-weather-app.fullPostgreSQLConnectionURL" . | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-username
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-password
                  key: password
