apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-weather-app-service
spec:
  selector:
    app: {{ .Release.Name }}-weather-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
